### ISSUE TITLE
load files when plotting

### ISSUE THREAD

**Issue by DejanDraschkow** [SebastianKorinth/eyEdu#3]
should we not just always load the data, so that it always gets the latest version? or we plot some old stuf.. 

`if(!exists("eyEdu.data")) {
    load(file = paste(raw.data.path, "eyEdu_data.Rda", sep = "")) 
}`

**Comment by SebastianKorinth** [comment]
The problem that reloading data is too time consuming is more a conceptual problem. Namely, the function does not refer to the eyEdu.data in the global enviorment, but creates its "own" enviroment. For further reading: https://www.datamentor.io/r-programming/environment-scope/

Anyhow, a more convenient way of scrolling through data is the new shiny app, which can be loaded after updating the package with: 
eyEduTrialViewer()
